name: build onecloud-2

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

      
    steps:
      - name: 释放磁盘空间
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
          
      - name: Checkout armbian
        run: |
          cd /home
          wget https://github.com/hy5528/OneCloud_armbian/releases/download/Armbian_Onecloud_jammy_5.9.0-docker/gcc-arm-9.2-2019.12-x86_64-arm-none-linux-gnueabihf.zip
          sudo chmod 777 gcc-arm-9.2-2019.12-x86_64-arm-none-linux-gnueabihf.zip
          unzip gcc-arm-9.2-2019.12-x86_64-arm-none-linux-gnueabihf.zip
          
      - name: Checkout armbian
        run: |
           git clone --depth=1 --branch=main https://github.com/hy5528/build.git build 
      
          
      - name: Build
        run: |
          cd build
          bash start.sh
          sudo chown $(id -u):$(id -g) -R output/
      
      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Armbian_Onecloud_jammy_5.9.0-docker
          append_body: true
          body_path: Release.md
          files: |
            build/output/amlimg/*
