name: build onecloud-2

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

      
    steps:
      - name: 释放磁盘空间
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
          
      - name: Check
        run: |
          cd /home
          sudo chmod 777 /home
          wget https://github.com/hy5528/OneCloud_armbian/releases/download/Armbian_Onecloud_jammy_5.9.0-docker/gcc-arm-9.2-2019.12-x86_64-arm-none-linux-gnueabihf.zip
          sudo chmod 777 gcc-arm-9.2-2019.12-x86_64-arm-none-linux-gnueabihf.zip
          sudo unzip gcc-arm-9.2-2019.12-x86_64-arm-none-linux-gnueabihf.zip
          
      - name: Checkout armbian
        run: |
           git clone --depth=1 --branch=main https://github.com/hy5528/build.git build 
      
         
      - name: Build
        run: |
          cd build
          ./compile.sh build BOARD=onecloud BRANCH=legacy BUILD_DESKTOP=no BUILD_MINIMAL=yes COMPRESS_OUTPUTIMAGE=img EXTRAWIFI=yes  KERNEL_CONFIGURE=no  DOWNLOAD_MIRROR=china MAINLINE_MIRROR=tuna RELEASE=bookworm BOOTSIZE=64  SYNC_CLOCK=no INCLUDE_HOME_DIR=yes  KERNEL_COMPILER=/gcc-arm-9.2-2019.12-x86_64-arm-none-linux-gnueabihf/bin/arm-none-linux-gnueabihf-

          sudo chown $(id -u):$(id -g) -R output/
      
      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Armbian_Onecloud_jammy_5.9.0-docker
          append_body: true
          body_path: Release.md
          files: |
            build/output/amlimg/*
